apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- portop-angular-app.yaml

patchesJson6902:
- target:
    kind: Ingress
    name: portop-angular-app-ingress
    version: v1
  path: portop-ingress-patch.yaml
